### ISSUE TITLE
Support for multiple machines?

### ISSUE THREAD

**Issue by sbrl** [srijanshetty/snips#5]
Can I have my snips stored on a remote serve  (say, via ssh?)

I use several linux machines - having access to my snips on all of them would be _awesome_!

**Comment by srijanshetty** [comment]
Interesting feature. I shall have a go at it over the weekend :smile:

**Comment by sbrl** [comment]
Thank you! :smile:

**Comment by srijanshetty** [comment]
Hey @sbrl, the way I try to overcome the issue of having multiple issues is to back my .snips folder in git. By doing so, not only can I backup my snips, but also refer to them when needed.

**Comment by sbrl** [comment]
Storing snips in a git repo sounds like a much better idea. Thanks for the suggestion!
